# Generated by Django 4.1 on 2022-08-30 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_address', models.CharField(max_length=500)),
                ('property_image', models.ImageField(blank=True, null=True, upload_to='review/images/property_image%y%m%d')),
                ('property_video', models.FileField(blank=True, null=True, upload_to='review/videos/property_video%y%m%d')),
                ('apartment_review', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='review/images/image1%y%m%d')),
                ('amenities_review', models.TextField()),
                ('image2', models.ImageField(blank=True, null=True, upload_to='review/images/image2%y%m%d')),
                ('landlord_review', models.TextField()),
                ('image3', models.ImageField(blank=True, null=True, upload_to='review/images/image3%y%m%d')),
                ('country', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('helpful', models.ManyToManyField(blank=True, related_name='helpful_count', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
