# Generated by Django 4.1 on 2022-09-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_testreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreview',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
