# Generated by Django 4.1 on 2022-09-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_testreview_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreview',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
