# Generated by Django 4.1 on 2022-09-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_testreview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='property_video',
            field=models.FileField(default='non', null=True, upload_to='review/videos/property_video%y%m%d'),
        ),
    ]
