# Generated by Django 4.1 on 2022-09-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_review_property_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='property_address',
            new_name='apartment_address',
        ),
        migrations.RemoveField(
            model_name='review',
            name='property_image',
        ),
        migrations.RemoveField(
            model_name='review',
            name='property_video',
        ),
        migrations.AddField(
            model_name='review',
            name='apartment_image',
            field=models.ImageField(blank=True, null=True, upload_to='review/images/apartment_image%y%m%d'),
        ),
        migrations.AddField(
            model_name='review',
            name='apartment_video',
            field=models.FileField(default='non', null=True, upload_to='review/videos/apartment_video%y%m%d'),
        ),
    ]
